apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-accessor-binding
  namespace: kube-service-catalog-controller-manager
roleRef:
  kind: Role
  name: configmap-accessor
subjects:
- kind: ServiceAccount
  namespace: kube-service-catalog-controller-manager
  name: service-catalog-controller
