apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openshift-service-catalog-controller-manager-operator
  namespace: openshift-service-catalog-controller-manager-operator
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: etcd_(debugging|disk|request|server).*
      sourceLabels:
      - __name__
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: metrics.openshift-service-catalog-controller-manager-operator.svc
  jobLabel: component
  namespaceSelector:
    matchNames:
    - openshift-service-catalog-controller-manager-operator
  selector:
    matchLabels:
      app: openshift-service-catalog-controller-manager-operator
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: openshift-service-catalog-controller-manager-operator
  namespace: openshift-service-catalog-controller-manager-operator
spec:
  groups:
    - name: svcat-controller-manager-enabled
      rules:
        - alert: ServiceCatalogControllerManagerEnabled
          annotations:
            summary: Indicates whether Service Catalog is enabled
          expr: |
            service_catalog_controller_manager_enabled > 0
          labels:
            severity: warning
