apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: openshift-svcat-controller-manager-operator-serving-cert
  labels:
    app: openshift-svcat-controller-manager-operator
  name: metrics
  namespace: openshift-svcat-controller-manager-operator
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: openshift-svcat-controller-manager-operator
  sessionAffinity: None
  type: ClusterIP
