apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-service-catalog-controller-manager-operator
  name: openshift-service-catalog-controller-manager-operator
  labels:
    app: openshift-service-catalog-controller-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-service-catalog-controller-manager-operator
  template:
    metadata:
      name: openshift-service-catalog-controller-manager-operator
      labels:
        app: openshift-service-catalog-controller-manager-operator
    spec:
      serviceAccountName: openshift-service-catalog-controller-manager-operator
      containers:
      - name: operator
        image: registry.svc.ci.openshift.org/openshift/origin-v4.0:cluster-svcat-controller-manager-operator
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        command: ["cluster-svcat-controller-manager-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        - "-v=4"
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
        env:
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        - name: IMAGE
          value: registry.svc.ci.openshift.org/openshift/origin-v4.0:service-catalog
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 400
          secretName: openshift-service-catalog-controller-manager-operator-serving-cert
          optional: true
      - name: config
        configMap:
          defaultMode: 440
          name: openshift-service-catalog-controller-manager-operator-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      tolerations:
      - operator: Exists
